# Configuração do Servidor
server.port=8080
# Configuração de Conexão com o Banco de Dados (PostgreSQL do Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_sales_processor
spring.datasource.username=datainfo_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuração do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configuração de Conexão com o RabbitMQ do Docker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest